### ISSUE TITLE
Undefined method_class for AMQ::Protocol::BodyFrame

### ISSUE THREAD

**Issue by buffpojken** [ruby-amqp/amqp#161]
I'm seeing this error quite often. I'm running multiple subscriptions to a fan/topic exchange. The code connecting is included here (http://pastie.org/private/est58llsrle17hqadztiq - #50-#59). I have no idea what's causing it but I see it fairly often. 

Any thoughts?

Stacktrace:
undefined method `method_class' for #<AMQ::Protocol::BodyFrame:0x007fb3f3db40a8>
Error raised during event loop: ["/Users/buffpojken/.rvm/gems/ruby-1.9.2-p180/gems/amq-client-0.9.10/lib/amq/client/async/adapter.rb:691:in`frameset_complete?'", "/Users/buffpojken/.rvm/gems/ruby-1.9.2-p180/gems/amq-client-0.9.10/lib/amq/client/async/adapter.rb:524:in `receive_frame'", "/Users/buffpojken/.rvm/gems/ruby-1.9.2-p180/gems/amq-client-0.9.10/lib/amq/client/async/adapters/event_machine.rb:321:in`receive_data'", "/Users/buffpojken/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'", "/Users/buffpojken/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run'", "world_simulator.rb:14:in `<main>'"

**Comment by colszowka** [comment]
@michaelklishin We've bumped into this issue when trying to add a feature that does bulk processing on our messaging layer. Is there a known limitation regarding the message size or why did you ask about the 128kb?

**Comment by michaelklishin** [comment]
@colszowka at some point there was a framing bug in amq-protocol that only affected messages exactly 128 KB in size, IIRC.
