### ISSUE TITLE
received messages increased by 200 on initial connection

### ISSUE THREAD

**Issue by nagas** [ruby-amqp/amqp#187]
When a consumer [1] connects to RabbitMQ and there are several hundred messages in the queue, it receives 200+prefetch_count messages [2].

It seems to be the case only when prefetch is set via AMQP::Channel constructor. It works as expected when set via `channel.prefetch()`.

[1] https://gist.github.com/nagas/8368511
[2] https://gist.github.com/nagas/8368484

I use latest RabbitMQ and amqp. Although I was able to reproduce it in every RabbitMQ/amqp versions I checked.

**Comment by spresnal** [comment]
I'm having an issue related to this with .NET rabbitmq client. The client fetches 200 messages on initial connect, then if it does nothing with those messages (I put a thread.sleep(70) in the event listener) the rabbitmq sends a shutdown signal and we dispose the client. When this happens those 200 prefetched messages get lost. What is the solution to this problem?

.NET rabbitmq client: 3.3.4
Rabbitmq server: 3.6.6

We do not use acknowledgements for performance reasons. Is there a better way we should handle this scenario or are message acknowledgments the best way?

**Comment by michaelklishin** [comment]
@spresnal this is not a support venue and this repository has nothing to do with the .NET client. Consider posting your questions to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

**Comment by michaelklishin** [comment]
I'm not sure why RabbitMQ "sends a shutdown signal" but presumably you close the channel or connection. The only solution to this problem is [to use manual acknowledgements](http://www.rabbitmq.com/confirms.html).

**Comment by michaelklishin** [comment]
[Channel prefetch](https://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/) and acknowledging N deliveries at a time is how you increase throughput without switching to the automatic (fire-and-forget) acknowledgement mode.
