### ISSUE TITLE
channel.on_error callback is deleted after recovery

### ISSUE THREAD

**Issue by rhex** [ruby-amqp/amqp#208]
Hi, I am using amqp gem recently, and find some issues.

### Reproduce Steps:
* define some channel.on_error callback, enable auto_recover
* start app using amqp gem
* produce some channel error, channel.on_error callback will be called
* restart rabbitmq, then my app will auto_recover
* if I produce channel error again, channel.on_error callback is not called.

### Root cause

I look into the code and find the root cause.

in Channel.rb, the reset_state! method will be called in handle_connection_interruption. In reset_state! 
only RECOVERY_EVENTS callbacks is reserved, others are deleted.
```ruby
@callbacks                     = @callbacks.delete_if { |k, v| !RECOVERY_EVENTS.include?(k) }
RECOVERY_EVENTS = [:after_connection_interruption, :before_recovery, :after_recovery].freeze
```

### My question

Why only RECOVERY_EVENTS is reserved?  in session.rb, the connection.on_errror does not follow this, it is still useful after auto recovery.

### Possible solution

Delete the relative code
```ruby
@callbacks                     = @callbacks.delete_if { |k, v| !RECOVERY_EVENTS.include?(k) }
```

**Comment by michaelklishin** [comment]
This was introduced in https://github.com/ruby-amqp/amq-client/commit/72c58044a496f22758749588f1b7a21a1adaa3c6 (amq-client has since been merged into amqp gem) and provides no context. I don't recall why this was done. One possible issue with preserving
every callback is that there are callbacks for queues that no longer exist after recovery.

Feel free to submit a PR that adds the callback you want to the list.

**Comment by rhex** [comment]
I could not understand your last sentence:
> One possible issue with preserving every callback is that there are callbacks for queues that no longer exist after recovery.

Based on my understanding, the queue callbacks are still preserved after recovery. Of course, it seems for server named queues, callbacks will be lost.

**Comment by michaelklishin** [comment]
Yes, that's what I was trying to say. I see no reason to clear other callbacks today. Just like I don't see any reason to use amqp gem and not Bunny, by the way ;)

**Comment by rhex** [comment]
Actually in the product I am working on bunny is used in the producer side while amqp is used in cosumer side. So I am wondering how bunny handles these. I will take a look. Thank you.☺

**Comment by michaelklishin** [comment]
@rhex just to make it clear, I'm all for merging your PR and doing a new point release but amqp gem isn't getting much attention in general.
