### ISSUE TITLE
undefined method next_channel_id error in channel.reuse method 

### ISSUE THREAD

**Issue by rhex** [ruby-amqp/amqp#209]
Hi, in the reuse method:
```
def reuse
      old_id = @id
      # must release after we allocate a new id, otherwise we will end up
      # with the same value. MK.
      @id    = self.class.next_channel_id
      @connection.release_channel_id(old_id)
        
      @channel_is_open_deferrable.fail
      @channel_is_open_deferrable = AMQP::Deferrable.new
       ...        
    end # reuse  
```
Actually self.class.next_channel_id no longer exists. So we need to change it to @connection.next_channel_id.
I find the only difference between reuse and auto_recover method is that reuse will release and reassign a new channel_id. So my question is, why do you reassign id here?  I think it is no need to do this.

**Comment by michaelklishin** [comment]
@rhex please submit a PR.

**Comment by michaelklishin** [comment]
`#reuse` is supposed to be used e.g. when manually recovering. `#auto_recover` is not, and should not be called by the user in the vast majority of cases.

**Comment by rhex** [comment]
OK, will submit a PR later, and Still I want to know:
 why reuse release and reassign a new channel_id?
