### ISSUE TITLE
amq-protocol 2.0.0 requires ruby 2.0

### ISSUE THREAD

**Issue by Suirtimed** [ruby-amqp/amqp#214]
The .gemspec requires amq-protocol >= 1.9.2 and unfortunately this is breaking for one of my applications that is not ready for ruby 2.0 yet.  Can this dependency be changed to ~> 1.9?

**Comment by michaelklishin** [comment]
@Suirtimed feel free to submit a PR and we'll cut a new point release.

**Comment by Suirtimed** [comment]
Perfect :)  Then if the desire is to move forward to ruby 2.0, a new 2.0.0 point release could be cut of amqp that can require amq-protocol ~> 2.0

**Comment by michaelklishin** [comment]
Merged in #217, I will cut a new release tomorrow.

**Comment by Suirtimed** [comment]
@michaelklishin Thank you very much!
