### ISSUE TITLE
Emit more specific error than `[amqp] Detected TCP connection failure`

### ISSUE THREAD

**Issue by nhooey** [ruby-amqp/amqp#222]
This [line in `lib/amqp/session.rb`](https://github.com/ruby-amqp/amqp/blob/c665bdca4bf36db761d7e87f3e2e73244b684e25/lib/amqp/session.rb#L638) emits `[amqp] Detected TCP connection failure` during the following conditions, which the comment lists:

* We close TCP connection down
* Our peer closes TCP connection down
* There is a network connection issue
* Initial TCP connection fails

Which is a lot of conditions to summarize in the word "failure".

The error should be specific so someone has a hope of troubleshooting the connection error.

**Comment by nhooey** [comment]
Awesome, thanks @michaelklishin! When can you cut a new release?

I'd like to get this in to [Sensu](https://github.com/sensu/sensu) as soon as possible.

**Comment by michaelklishin** [comment]
In the next few days.

**Comment by michaelklishin** [comment]
@nhooey I've released `1.5.3` (depends on [amq-protocol](https://rubygems.org/gems/amq-protocol) 1.9.x, supports Ruby 1.9) and `1.6.0` (depends on amq-protocol 2.0.x, supports Ruby 2.0+).

In general, I'd highly recommend Sensu to switch to [Bunny](http://rubybunny.info/). amqp gem is not being actively maintained.

**Comment by nhooey** [comment]
@portertech What do you think about cutting a new release of Sensu using this version, and then switching to Bunny?

**Comment by nhooey** [comment]
Thanks for releasing his on short notice, @michaelklishin.
