### ISSUE TITLE
Changes in the behavior regarding cancel callback execution.

### ISSUE THREAD

**Issue by maattdd** [ruby-amqp/amqp#228]
Hi,

Before commit 3ddddc68b32250c65e4db32d07060b33ee6495ee, the block ok_cancel was called after the method unregister_with_* and clear_callbacks(*). Now, it is called before. 

This change of behavior breaks one of our test, but I'm not sure it can actually be considered a bug. 

The fix would be as simple as changing the position of the  self.exec_callback_once(:cancel, cancel_ok) a bit down in handle_cancel_ok(cancel_ok).

However, relying on this behavior might be considered a code smell... 👃

**Comment by michaelklishin** [comment]
Your application shouldn't depend on this ordering. `unregister_with_*` are not events meant to be used by applications. I don't see how callback-related ones are of much value for consumers.

**Comment by michaelklishin** [comment]
I think the commit message in 3ddddc68b32250c65e4db32d07060b33ee6495ee hints at the fact that the previous order wasn't a good idea.

**Comment by maattdd** [comment]
Well it is possible to change the order but still fix #198 by doing all the work in handle_cancel_ok, just executing the callback at the end of this method instead of the beginning (and before clear_callbacks :cancel obviously 🐙 ).
But as I said, I don't think we should rely on this behavior anyway.
