### ISSUE TITLE
attributes defined twice

### ISSUE THREAD

**Issue by utilum** [ruby-amqp/amqp#233]
Instance attributes `server_properties`, `server_capabilities` and `server_locales` are defined twice each, in `lib/amqp/session.rb`, once under `# @api public` and then again under `# @group Broker information`. 

This raises `method redefined` warnings. Does it server anything? I'd be happy to patch.

**Comment by michaelklishin** [comment]
There is no big idea behind it, it's a yet another leftover from the amq-client integration days. Feel free to look into a PR. We should probably remove the one that's defined first (this would decrease the chance of introducing a breaking change).
