### ISSUE TITLE
AMQP doesn't share AMQ::Settings

### ISSUE THREAD

**Issue by Tensho** [ruby-amqp/amqp#236]
Despite of the initial intention to use `amq-protocol` as a common place for the shared code between `bunny` and `amqp` gems, the last one doesn't use `AMQ::Settings` at all. There is own copy `AMQP::Settings` module, that combines `AMQ::Settings` and `AMQ::URI` functionality from `amq-protocol` gem.

[Here](https://github.com/ruby-amqp/bunny/pull/534) I added URI query params support to `bunny` and would like to do the same for `amqp`, but seems like it will be problematic, as far as `amqp` has it's own code for that and doesn't share that part with `amq-protocol`.

Should we transfer `amqp` to use `AMQ::Settings` (`amq-protocol`) before duplicating URI query params adoption from the client side?

**Comment by michaelklishin** [comment]
`amq-protocol` is already a dependency, so I don't see why not.

**Comment by michaelklishin** [comment]
Why was this closed?

**Comment by Tensho** [comment]
It's an issue that was agreed with a plan, I'm going to provide PR ^_^
Nothing more to discuss here.

**Comment by michaelklishin** [comment]
Fair enough, I close issues once their PR[s] is merged, so let's reopen.
